zookeeper:
  image: dockerkafka/zookeeper
  ports:
   - "2181:2181"
   - "2888:2888"
   - "3888:3888"
   - "5000:5000"

kafka-0:
  image: dockerkafka/kafka
  ports:
    - "9092"
  links:
    - zookeeper:zookeeper

kafka-1:
  image: dockerkafka/kafka
  ports:
    - "9092"
  links:
    - zookeeper:zookeeper
  volumes:
    - ./config1:/opt/kafka_2.10-0.8.2.1/config

kafka-2:
  image: dockerkafka/kafka
  ports:
    - "9092"
  links:
    - zookeeper:zookeeper
  volumes:
    - ./config2:/opt/kafka_2.10-0.8.2.1/config

kafka-manager:
  image: dockerkafka/kafka-manager
  environment:
    - ZK_HOSTS=zookeeper:2181
  ports:
    - "9000:9000"
  links:
    - zookeeper:zookeeper
