zookeeper:
  image: dockerkafka/zookeeper
  ports:
   - "2181:2181"
   - "2888:2888"
   - "3888:3888"
   - "5000:5000"

kafka-0:
  image: dockerkafka/kafka
  ports:
    - "9092:9092"
  links:
    - zookeeper:zookeeper
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
    KAFKA_ADVERTISED_PORT: 9092

kafka-1:
  image: dockerkafka/kafka
  ports:
    - "9091:9092"
  links:
    - zookeeper:zookeeper
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
    KAFKA_ADVERTISED_PORT: 9091
  volumes:
    - ./config1:/opt/kafka_2.10-0.8.2.1/config

kafka-2:
  image: dockerkafka/kafka
  ports:
    - "9090:9092"
  links:
    - zookeeper:zookeeper
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
    KAFKA_ADVERTISED_PORT: 9090
  volumes:
    - ./config2:/opt/kafka_2.10-0.8.2.1/config

kafka-manager:
  image: dockerkafka/kafka-manager
  environment:
    - ZK_HOSTS=zookeeper:2181
  ports:
    - "9000:9000"
  links:
    - zookeeper:zookeeper
