zookeeper:
  image: dockerkafka/zookeeper
  ports:
   - "2181:2181"
   - "2888:2888"
   - "3888:3888"
   - "5000:5000"

kafka-0:
  image: cegeka/kafka
  ports:
    - "9090:9092"
  links:
    - zookeeper:zookeeper
  volumes:
      - ./config0:/opt/kafka_2.10-0.9.0.1/config

kafka-1:
  image: cegeka/kafka
  ports:
    - "9091:9092"
  links:
    - zookeeper:zookeeper
  volumes:
    - ./config1:/opt/kafka_2.10-0.9.0.1/config

kafka-2:
  image: cegeka/kafka
  ports:
    - "9092:9092"
  links:
    - zookeeper:zookeeper
  volumes:
    - ./config2:/opt/kafka_2.10-0.9.0.1/config

kafka-manager:
  image: dockerkafka/kafka-manager
  environment:
    - ZK_HOSTS=zookeeper:2181
  ports:
    - "9000:9000"
  links:
    - zookeeper:zookeeper

spark:
  image: sequenceiq/spark
  ports:
    - "8088:8088"
    - "8042:8042"
    - "4040:4040"
  links:
    - zookeeper:zookeeper
    - kafka-0:kafka
  volumes:
    - ./spark:/app
